---
output:
 html_document:
  theme: yeti
---

<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<style>

code{
  background-color:#f2f2f2;
  border-radius: 25px;
}
 
span.co{
  color:#000080;
  font-weight: bold;
}
 
img{
  display: block;
  padding-left: 15px;
  padding-right: 15px;
  padding-top: 10px;
  padding-bottom: 10px;
}

p{
  text-align: left;
  font-size: 18px;
}

ul, ol{
  line-height: 27px;
  text-align: left;
  font-size: 18px;
  margin-left: 0px;
}
 
blockquote{
  font-size: 18px;
  border-left: 8px solid #292093;
  background-color: #e6ffff;
  padding-left: 16px;
  padding-right: 16px;
}
 
.row{
  margin: auto;
}
 
table {
  border-collapse: collapse;
}

table, td, th {
  border: 1px solid black;
  padding: 5px;
  text-align: center;
  vertical-align: middle;
}
 
 /* Create two equal columns that floats next to each other */
.column {
  float: left;
  width: 50%;
  padding: 10px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

.roundBorder {
  border-radius: 25px;
  border: 5px solid #30288C;
  background: #D6EAF8;
  padding-left: 20px;
  padding-right: 20px;
  padding-top: 10px;
  padding-bottom: 10px;
}

.roundBorderBlack {
  border-radius: 25px;
  border: 10px solid #D3D3D3;
  padding-left: 20px;
  padding-right: 20px;
  padding-top: 10px;
  padding-bottom: 10px;
}

.roundBorderBlackEx {
  border-radius: 5px;
  border: 5px solid #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  padding-top: 2px;
}

.roundBorderEx {
  border-radius: 3px;
  border: 5px solid #30288C;
  background: #D6EAF8;
  padding-left: 5px;
  padding-right: 5px;
  padding-top: 2px;
}

.tt {
    position: relative;
    display: inline-block;
    class: inline; 
    font-weight: bold;
    font-family: "Avenir";
    font-size: 18px;
    border-bottom: 1px black;
}

/* Tooltip text */
.tt .ttText {
    visibility: hidden;
    font-weight: normal;
    font-size: 18px;
    width: 200px;
    background-color: black;
    border: 1px solid black;
    color: white;
    text-align: left;
    padding: 5px;
    border-radius: 6px;
    position: absolute;
    z-index: 1;
}

/* Show the tooltip text when you mouse over the tooltip container */
.tt:hover .ttText {
    visibility: visible;
}

</style>

<h2>R Homework, Lesson 6: Data wrangling</h2>
<hr>
<p>Please use the file <a href = "https://smbc-nzp.github.io/lesson6_homeworkQuestions.R" download>`lesson6_homeworkQuestions.R`</a> to complete this assignment. You may find some of the questions in this assignment very easy and some prohibitively challenging. Just do what you can. This exercise is to help give you more practice with R and to help me evaluate the level of understanding of workshop participants and isolate current weak points in understanding. I am also curious the length of time it takes to complete this assignment. Please estimate the total time you spend with the assignment (even if you are unable to complete all of the questions). Please be sure to:</p>

<ul>
<li>Complete all steps in the space provided on the script.</li>
<li>You must run the complete set up section of the script prior to answering questions!</li>
<li>Each question can be answered using tools that we have covered thus far in the workshop. Please use only these tools to answer questions.</li>
<li>Complete all steps in one line of code unless you are instructed otherwise.</li>
<li>Do not assign any object names unless you are instructed otherwise.</li> 
</ul>
<br>
<p>Once completed, please save your rScript as `rHomework4_[your last name]-[your first name].R` (for example, my homework would be titled `rHomework4_Evans-Brian.R`) and <a href="mailto:evansbr@si.edu">email it to me</a>. Please use the subject line "rWorkshop, assignment 2" in your email. In the body of your email, please include the amount of time the assignment took to complete.</p>
<hr>
<h3><b>Set up:</b></h3>
<br>
```{r setup, eval = FALSE}
# Load libraries:

library(RCurl)
library(lubridate)

# Load a source script:

script <-
  getURL(
    "https://raw.githubusercontent.com/bsevansunc/workshop_languageOfR/master/sourceCode.R"
  )

# Evaluate then remove the source script:

eval(parse(text = script))

rm(script)
```
<hr>

<ol>
<li>Calculate the population of the Bahamas from 1995-2013. Return your results as a two-column data frame with the columns year and population.</li>
<br><br>
<li>Use group_by and summarize to calculate the population density of each region. Return your results as a two-column data frame with the columns region and popDensity.</li>
<br><br>
<li>Calculate the total number of each diet class observed at site "apple" in  2009. Return your results as a two-column data frame with the columns diet and count.</li>
<br><br>
<li>Calculate the average mass and number of characters associated with each species of the Star Wars universe. Return your results as a three-column data frame with the columns: species, nCharacters, and meanMass.</li>
<br><br>
<li>You have developed a derived variable, "petalShape" to describe Iris flowers. This variable is defined as:

$$petalShape = \frac{petalLength}{petalWidth}$$
Calculate the average (mean) shape of petals in the iris dataset. Return your results as a two-column data frame with the columns species and petalShape_mean.</li>
<br>
</ol>
<br>
<hr>