<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title></title>

<script src="OccupancyDemo_Oven_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="OccupancyDemo_Oven_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="OccupancyDemo_Oven_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="OccupancyDemo_Oven_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="OccupancyDemo_Oven_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="OccupancyDemo_Oven_files/navigation-1.1/tabsets.js"></script>
<link href="OccupancyDemo_Oven_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="OccupancyDemo_Oven_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">




</div>


<head>
<link rel="stylesheet" href="N:/Capacity Building and Academic Programs/SI-Mason Grad & Prof Training/Individual Courses--Folders/Bird Migration/2018/Materials/Distance/Exercises"> <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<div id="occupancy-modeling-demo-exercise" class="section level1">
<h1>Occupancy Modeling Demo Exercise</h1>
<p>
<i>Joe Kolowski, Ph.D.</i>
</p>
<div id="project-description-and-context" class="section level2">
<h2>Project Description and Context</h2>
<p><img style="float:right" src="images/TX_Ovenbird01.jpg" /></p>
<p>We are working here with a dataset provided by Mike Hallworth, and collected at Hubbard Brook New Hampshire, USA. The full data set at Hubbard Brook had 373 point count survey locations systematically placed throughout Hubbard Brook Valley along 15 transects. Our data set includes 296 of these survey points. Point counts were conducted 4 times per year, and have been collected since 1999. Here we are working with a single year’s data. Surveys typically started at the end of May, and all 4 surveys were typically done within a month. Each point count was split into 3 consecutive “periods” of 3 minutes, 20 seconds each (so the observer spent 10 minutes at each location during a survey). These data are part of a large, long-term study focused on investigating many aspects of songbird ecology including habitat use, recruitment, species richness and abundance, and many others. In this demo we’ll be working only with the ovenbird (OVEN) information, but the dataset includes records of Red-eyed Vireo (REVI), Black-throated Blue Warbler (BTBW), and Blackburnian Warbler (BLBW). Here our goal is to assess what factors influence occupancy probability of ovenbirds in this landscape, while accounting for factors that may influence detection.</p>
</div>
<div id="exercise-objectives" class="section level2">
<h2>Exercise Objectives</h2>
<ul>
<li>Learn how to import and format raw data from point count field studies for occupancy analysis</li>
<li>Learn how to prepare data for use in the package <code>unmarked</code> and how to summarize that data</li>
<li>Run a single season occupancy modeling analysis with covariates on occupancy and detection probability</li>
<li>Become familiar with output results of occupancy models and how to compare models using model selection approaches</li>
<li>Create response curves for model covariates to assist in model interpretation</li>
</ul>
<div id="librariessetup" class="section level3">
<h3>Libraries/Setup</h3>
<p>Let’s first call the packages we’ll need in this exercise. Use <code>install.packages</code> if you do not have these packages already on your machine.</p>
<pre class="r"><code>library(unmarked)
library(tidyverse)
library(lubridate) #for the `yday` function</code></pre>
</div>
<div id="data-import-and-exploration" class="section level3">
<h3>Data Import and Exploration</h3>
<p>
<p>We can bring in data using our <code>read.csv</code> command, with our data files stored in our course dropbox folder as opposed to on our local computer.</p>
<pre class="r"><code>counts &lt;- 
  read.csv(&#39;https://www.dropbox.com/s/fdotemoww8qdu8l/countData.csv?dl=1&#39;)

visits &lt;- 
  read.csv(&#39;https://www.dropbox.com/s/wr961cx2lxxfssp/visitData.csv?dl=1&#39;)

siteCovs &lt;-
  read.csv(&#39;https://www.dropbox.com/s/gbrxt85jwid2t55/siteData.csv?dl=1&#39;)</code></pre>
<p>
<p>Let’s have a look at what these files contain. The countData file contains all observations during this study of each of our 5 bird species, across 4 sampling ocassions. Although the plot ID goes to 400, every plot number is not represented in this data set. We can use the <code>unique</code> function to see that we actually have 296 plots in the data set.</p>
<pre class="r"><code>head(counts)</code></pre>
<pre><code>##   plot replicate period species n
## 1    1         0      1    BTBW 1
## 2    1         0      1    REVI 1
## 3    1         0      2    BLBW 1
## 4    1         0      2    BTBW 1
## 5    1         0      2    REVI 1
## 6    1         0      3    BTBW 1</code></pre>
<pre class="r"><code>str(counts)</code></pre>
<pre><code>## &#39;data.frame&#39;:    8291 obs. of  5 variables:
##  $ plot     : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ replicate: int  0 0 0 0 0 0 1 1 1 1 ...
##  $ period   : int  1 1 2 2 2 3 1 1 2 3 ...
##  $ species  : Factor w/ 5 levels &quot;BLBW&quot;,&quot;BTBW&quot;,..: 2 5 1 2 5 2 2 5 5 2 ...
##  $ n        : int  1 1 1 1 1 1 1 3 1 1 ...</code></pre>
<pre class="r"><code>summary(counts)</code></pre>
<pre><code>##       plot         replicate         period      species    
##  Min.   :  1.0   Min.   :0.000   Min.   :1.000   BLBW:1200  
##  1st Qu.: 88.0   1st Qu.:1.000   1st Qu.:1.000   BTBW:1766  
##  Median :180.0   Median :2.000   Median :2.000   BTNW:1742  
##  Mean   :192.3   Mean   :1.514   Mean   :2.003   OVEN:1730  
##  3rd Qu.:309.0   3rd Qu.:3.000   3rd Qu.:3.000   REVI:1853  
##  Max.   :400.0   Max.   :3.000   Max.   :3.000              
##        n        
##  Min.   :1.000  
##  1st Qu.:1.000  
##  Median :1.000  
##  Mean   :1.208  
##  3rd Qu.:1.000  
##  Max.   :4.000</code></pre>
<pre class="r"><code>length(unique(counts$plot))</code></pre>
<pre><code>## [1] 296</code></pre>
<p>
<p>The siteCovs file contains covariates associated wtih these 296 sampled sites. Here we will just be working with elevation, aspect and slope as site covariates.</p>
<pre class="r"><code>head(siteCovs)</code></pre>
<pre><code>##   plot elevation    aspect     slope
## 1    1  818.6771 0.1894924 0.1808274
## 2    2  856.6822 1.3802499 0.2443474
## 3    3  842.4990 2.3006748 0.4442618
## 4    4  846.7539 5.8217979 0.1894956
## 5    5  866.9452 5.5484516 0.1105239
## 6    6  894.7712 5.3278027 0.1652264</code></pre>
<pre class="r"><code>str(siteCovs)</code></pre>
<pre><code>## &#39;data.frame&#39;:    296 obs. of  4 variables:
##  $ plot     : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ elevation: num  819 857 842 847 867 ...
##  $ aspect   : num  0.189 1.38 2.301 5.822 5.548 ...
##  $ slope    : num  0.181 0.244 0.444 0.189 0.111 ...</code></pre>
<pre class="r"><code>summary(siteCovs)</code></pre>
<pre><code>##       plot          elevation         aspect            slope        
##  Min.   :  1.00   Min.   :252.0   Min.   :0.01254   Min.   :0.01818  
##  1st Qu.: 89.75   1st Qu.:512.6   1st Qu.:1.03913   1st Qu.:0.14567  
##  Median :182.50   Median :611.3   Median :2.35125   Median :0.20885  
##  Mean   :192.46   Mean   :612.1   Mean   :2.48843   Mean   :0.21922  
##  3rd Qu.:307.25   3rd Qu.:733.0   3rd Qu.:3.51656   3rd Qu.:0.28442  
##  Max.   :400.00   Max.   :935.5   Max.   :6.21228   Max.   :0.61949</code></pre>
<p>
<p>We also have survey covariates as well. These are covariates associated with each visit to each site. In other words, the values can vary across our 4 ocassions. That means we have 4*296 rows of data here. We have time of survey, observer, and two climatic variables representing the cloud cover (sky) and wind level (wind).</p>
<pre class="r"><code>head(visits)</code></pre>
<pre><code>##   plot replicate      date    time observer sky wind
## 1  314         0 5/22/2015 5:32:00       CH   0    0
## 2  337         0 5/21/2015 5:51:00       CH   0    0
## 3  392         0 5/21/2015 6:10:00       CH   0    0
## 4  393         0 5/21/2015 6:27:00       CH   1    0
## 5  394         0 5/21/2015 6:48:00       CH   1    0
## 6  352         0 5/21/2015 5:30:00      DJW   1    1</code></pre>
<pre class="r"><code>str(visits)</code></pre>
<pre><code>## &#39;data.frame&#39;:    1184 obs. of  7 variables:
##  $ plot     : int  314 337 392 393 394 352 339 395 391 390 ...
##  $ replicate: int  0 0 0 0 0 0 0 0 0 0 ...
##  $ date     : Factor w/ 31 levels &quot;5/21/2015&quot;,&quot;5/22/2015&quot;,..: 2 1 1 1 1 1 1 1 1 1 ...
##  $ time     : Factor w/ 275 levels &quot;10:00:00&quot;,&quot;10:01:00&quot;,..: 8 26 46 64 85 6 7 104 154 172 ...
##  $ observer : Factor w/ 4 levels &quot;AJS&quot;,&quot;CH&quot;,&quot;DJW&quot;,..: 2 2 2 2 2 3 1 2 2 2 ...
##  $ sky      : int  0 0 0 1 1 1 2 1 1 0 ...
##  $ wind     : int  0 0 0 0 0 1 1 0 0 0 ...</code></pre>
<pre class="r"><code>summary(visits)</code></pre>
<pre><code>##       plot          replicate           date          time      observer 
##  Min.   :  1.00   Min.   :0.00   6/12/2015: 53   5:30:00:  51   AJS:308  
##  1st Qu.: 89.75   1st Qu.:0.75   6/25/2015: 51   5:45:00:  15   CH :302  
##  Median :182.50   Median :1.50   6/3/2015 : 51   6:03:00:  11   DJW:327  
##  Mean   :192.46   Mean   :1.50   6/18/2015: 49   8:33:00:  11   JDW:247  
##  3rd Qu.:307.25   3rd Qu.:2.25   6/6/2015 : 49   5:47:00:  10            
##  Max.   :400.00   Max.   :3.00   6/7/2015 : 49   6:22:00:  10            
##                                  (Other)  :882   (Other):1076            
##       sky             wind       
##  Min.   :0.000   Min.   :0.0000  
##  1st Qu.:0.000   1st Qu.:0.0000  
##  Median :1.000   Median :1.0000  
##  Mean   :1.119   Mean   :0.9451  
##  3rd Qu.:2.000   3rd Qu.:1.0000  
##  Max.   :5.000   Max.   :6.0000  
## </code></pre>
</div>
<div id="data-formatting" class="section level3">
<h3>Data Formatting</h3>
<p>When data is collected, we often have what our <code>counts</code> object looks like, a row for each observation. This demo analysis will focus on the ovenbird though, so we need to <code>filter</code> the data to pull out only the ovenbird observations. In addition we only need the data included in the columns <code>replicate</code> and <code>plot</code> so we’ll use <code>select</code> to pull out only those columns. Also, the original data recorded the actual number of birds seen at each visit of each species, but here we will just be interested in whether or not the species was seen at all (i.e. 1 vs. 0). We’ll use <code>mutate</code> to create a new column in our new <code>ovenCounts</code> object, with a 1 for each row, indicating the species was present. Finally, for occupancy we don’t necessarily care if our species was seen multiple times across sampling ‘periods’, within the same site visit. So we’ll use <code>distinct</code> to keep only 1 record of our species, within each unique combination of replicate and plot.</p>
<pre class="r"><code>ovenCounts &lt;-
  counts %&gt;%
  filter(species == &#39;OVEN&#39;) %&gt;%
  select(plot, replicate) %&gt;%
  mutate(n = 1) %&gt;%
  distinct</code></pre>
<p>
<p>Let’s look at <code>ovencounts</code> and make sure we understand what the code above has done.</p>
<pre class="r"><code>head(ovenCounts)</code></pre>
<pre><code>##   plot replicate n
## 1    1         1 1
## 2    1         3 1
## 3    2         1 1
## 4    2         2 1
## 5    2         3 1
## 6    3         1 1</code></pre>
<p>
Our data is almost ready, but remember that the rows we have represent all the observations. Occupancy modeling draws key pieces of information from absences as well. Our <code>visits</code> object let’s us know which sites were visited, regardless of what was seen there. We need to use this information to make sure we represent every site visit, even when the species wasn’t seen. The code below first <code>select</code>s the plot and replicate columns from the <code>visits</code> object. We then use <code>left_join</code> to essentially merge <code>visits</code> with <code>ovenCounts</code>, using our plot and replicate columns. The <code>left_join</code> indicates we want to keep everything in the <code>visits</code> object (i.e. all the sites). We then use the amazing <code>spread</code> function to expand this data into a full matrix, according to the information in replicate, which is each of 4 values (0-3). For any situation where there is not an existing combination of replicate and plot, a zero will be <code>fill</code>ed. These are our absences. Lastly we will remove the plot column (column 1) with the <code>select</code> function and convert the object to a matrix.
<p>
<p><em>Note that the spread function below will not work perfectly if one did not visit each site the same number of times, even though this is perfectly acceptable for a study design. Other R functions could be used to account for this situation.</em></p>
<pre class="r"><code>detectionFrameOven &lt;-
  visits %&gt;%
  select(plot, replicate) %&gt;%
  left_join(ovenCounts,
            by = c(&#39;plot&#39;, &#39;replicate&#39;)) %&gt;%
  distinct %&gt;%
  spread(replicate, n, fill = 0) %&gt;%
  select(-1) %&gt;%
  as.matrix</code></pre>
<p>
<p>Let’s confirm what we have now, which should be a matrix of 296 sites (rows) and 4 occasions (columns) indicating in which situations the species was observed or not observed.</p>
<pre class="r"><code>head(detectionFrameOven)</code></pre>
<pre><code>##      0 1 2 3
## [1,] 0 1 0 1
## [2,] 0 1 1 1
## [3,] 0 1 0 0
## [4,] 0 1 1 0
## [5,] 0 1 1 1
## [6,] 0 0 1 1</code></pre>
<p>
<p>Finally we need to create a list, which includes our survey covariates. Each element in the list should be a dataframe, with a row for each site, and a column for each sampling ocassion. Here again, as above, we use the <code>select</code> function to choose which columns of data we want from the <code>visits</code> object, then we use the <code>spread</code> function to expand the data in a long-form matrix. We then remove the plot column, as it is no longer needed and cannot remain in these data frames. We also need to change our time and date variables from factor variables to something we can analyze.</p>
<pre class="r"><code>obsCovs &lt;-
  list(
    observer = visits %&gt;%
      select(plot, replicate, observer) %&gt;%
      spread(replicate, observer) %&gt;%
      mutate(plot = NULL),
    timeOfDay = visits %&gt;%
      select(plot, replicate, time) %&gt;%
      mutate(time = as.numeric(time)) %&gt;%
      spread(replicate, time) %&gt;%
      mutate(plot = NULL),
    dayOfYear = visits %&gt;%
      select(plot, replicate, date) %&gt;%
      mutate(date = yday(strptime(date, format = &quot;%m/%d/%Y&quot;))) %&gt;%
      spread(replicate, date) %&gt;%
      mutate(plot = NULL),
    sky = visits %&gt;%
      select(plot, replicate, sky) %&gt;%
      spread(replicate, sky) %&gt;%
      mutate(plot = NULL),
    wind = visits %&gt;%
      select(plot, replicate, wind) %&gt;%
      spread(replicate, wind) %&gt;%
      mutate(plot = NULL)
  )</code></pre>
<p>
<p>Our data are now ready for the <code>unmarkedFrameOccu</code> function which prepares our data for occupancy analysis.We need to provide three objects, the detection matrix, our site covariates data frame, and a list of dataframes for our observation/survey covariates.</p>
<pre class="r"><code>umfOven &lt;-
  unmarkedFrameOccu(y = detectionFrameOven,
  siteCovs = siteCovs,
  obsCovs = obsCovs)</code></pre>
<p>
<p>We can look at a general summary of the data using <code>summary</code> on this object</p>
<pre class="r"><code>summary(umfOven)</code></pre>
<pre><code>## unmarkedFrame Object
## 
## 296 sites
## Maximum number of observations per site: 4 
## Mean number of observations per site: 4 
## Sites with at least one detection: 258 
## 
## Tabulation of y observations:
##   0   1 
## 457 727 
## 
## Site-level covariates:
##       plot          elevation         aspect            slope        
##  Min.   :  1.00   Min.   :252.0   Min.   :0.01254   Min.   :0.01818  
##  1st Qu.: 89.75   1st Qu.:512.6   1st Qu.:1.03913   1st Qu.:0.14567  
##  Median :182.50   Median :611.3   Median :2.35125   Median :0.20885  
##  Mean   :192.46   Mean   :612.1   Mean   :2.48843   Mean   :0.21922  
##  3rd Qu.:307.25   3rd Qu.:733.0   3rd Qu.:3.51656   3rd Qu.:0.28442  
##  Max.   :400.00   Max.   :935.5   Max.   :6.21228   Max.   :0.61949  
## 
## Observation-level covariates:
##  observer    timeOfDay       dayOfYear          sky       
##  AJS:308   Min.   :  1.0   Min.   :141.0   Min.   :0.000  
##  CH :302   1st Qu.: 59.0   1st Qu.:153.0   1st Qu.:0.000  
##  DJW:327   Median :121.0   Median :162.0   Median :1.000  
##  JDW:247   Mean   :125.3   Mean   :162.7   Mean   :1.119  
##            3rd Qu.:191.0   3rd Qu.:173.8   3rd Qu.:2.000  
##            Max.   :275.0   Max.   :187.0   Max.   :5.000  
##       wind       
##  Min.   :0.0000  
##  1st Qu.:0.0000  
##  Median :1.0000  
##  Mean   :0.9451  
##  3rd Qu.:1.0000  
##  Max.   :6.0000</code></pre>
<p>
This show us naive occupancy here is 87%, that is ovenbirds were found at 87% of the sites.
<p>
<p>The <code>unmarked</code> package also has a built in <code>plot</code> setting to show you detections across sites and ocassions. It is a bit crazy looking, but gives at least some sense of how your presences and absences fall out over sites and ocassions.</p>
<pre class="r"><code>plot(umfOven)</code></pre>
<p><img src="OccupancyDemo_Oven_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
<div id="model-fitting-and-model-selection---occupancy-covariates" class="section level3">
<h3>Model Fitting and Model Selection - Occupancy covariates</h3>
<p>Let’s run some models! First let’s look at factors influencing occupancy, while holding a general model for detection. We’ll try all combinations of our 3 site covariates. Note that in the model formula statement, the detection model comes first, followed by the occupancy model.</p>
<pre class="r"><code>Psidot_pFull &lt;- occu( ~ wind + sky + dayOfYear + observer + timeOfDay 
                      ~ 1, data = umfOven) 
PsiElev_pFull &lt;- occu( ~ wind + sky + dayOfYear + observer + timeOfDay 
                       ~ elevation, data = umfOven)
PsiSlope_pFull &lt;- occu( ~ wind + sky + dayOfYear + observer + timeOfDay 
                        ~ slope, data = umfOven)
PsiAspect_pFull &lt;- occu( ~ wind + sky + dayOfYear + observer + timeOfDay 
                        ~ aspect, data = umfOven)
PsiAspectElev_pFull &lt;- occu( ~ wind + sky + dayOfYear + observer + timeOfDay 
                        ~ aspect + elevation, data = umfOven)
PsiAspectSlope_pFull &lt;- occu( ~ wind + sky + dayOfYear + observer + timeOfDay 
                        ~ aspect + slope, data = umfOven)
PsiSlopeElev_pFull &lt;- occu( ~ wind + sky + dayOfYear + observer + timeOfDay 
                        ~ slope + elevation, data = umfOven)
PsiAspectSlopeElev_pFull &lt;- occu( ~ wind + sky + dayOfYear + observer + timeOfDay 
                        ~ aspect +slope + elevation, data = umfOven)</code></pre>
<p>
<p>Once we have our models run, we can use the <code>fitList</code> function to compile the models together, in preparation for model selection. We then use the <code>modSel</code> function to bring together the model results and compare using AIC-based approaches. Note that putting parentheses around code that creates something, will print that object automatically to the console</p>
<pre class="r"><code>ObsModsO &lt;- fitList(Psidot_pFull,PsiElev_pFull,PsiSlope_pFull, PsiAspect_pFull, PsiAspectElev_pFull, PsiAspectSlope_pFull,PsiSlopeElev_pFull,PsiAspectSlopeElev_pFull)
(ObsModsRank &lt;- modSel(ObsModsO))</code></pre>
<pre><code>##                          nPars     AIC delta  AICwt cumltvWt
## PsiAspectElev_pFull         11 1446.07  0.00 0.4588     0.46
## PsiAspectSlopeElev_pFull    12 1446.61  0.54 0.3499     0.81
## PsiAspect_pFull             10 1448.81  2.74 0.1163     0.92
## PsiAspectSlope_pFull        11 1449.94  3.87 0.0663     0.99
## PsiElev_pFull               10 1455.82  9.76 0.0035     0.99
## Psidot_pFull                 9 1456.74 10.67 0.0022     1.00
## PsiSlopeElev_pFull          11 1456.97 10.90 0.0020     1.00
## PsiSlope_pFull              10 1458.15 12.08 0.0011     1.00</code></pre>
<p>
<p>We can see that our best model includes both aspect and elevation. Before we focus on interpreting the results, let’s see if we can simplify our detection model by trying various more simple combinations of our 5 survey covariates, along with our best occupancy model from above. Unfortunately, with even just 5 covariates, we have a lot of potential models we can test…27 to be exact! You’ll note below that I’ve had to specify starting values to get some of these models to run. We run into some challenges with this dataset, because ovenbirds were seen at some many of our sites. This reduces the amount of variation available for different covariates to try to explain. This also means that for some levels or combinations of covariates, there may be no sites, or ocassions, where birds were not seen. This all causes some models to fail to find maximum likelihood values, and starting values can help with this. These starting values represent estimated coefficient values for all model parameters. To get these, we can take a model that did run, and use the <code>coef</code> function to look at the coefficient values and help us get a sense of what we should use.</p>
</div>
<div id="model-fitting-and-selection---detection-covariates" class="section level3">
<h3>Model Fitting and Selection - Detection covariates</h3>
<pre class="r"><code>PsiAspectElev_pdot &lt;- occu( ~ 1
                            ~ aspect + elevation,
                            data = umfOven,
                            starts = c(.6,-.4, .004, 1)
)
PsiAspectElev_pwind &lt;- occu( ~ wind
                             ~ aspect + elevation,
                             data = umfOven,
                             starts = c(.6,-.4, .004, 2.3,-.15)
)
PsiAspectElev_psky &lt;- occu( ~ sky
                            ~ aspect + elevation,
                            data = umfOven,
                            starts = c(.6,-.4, .004, 2.3,-.07)
)
PsiAspectElev_pobs &lt;- occu( ~ observer
                            ~ aspect + elevation,
                            data = umfOven,
                            starts = c(.6, -.4, .004, 1.3, -.6, -.9, -.09)
)
PsiAspectElev_pday &lt;- occu(~ dayOfYear
                           ~ aspect + elevation, data = umfOven)

PsiAspectElev_ptime &lt;- occu(~ timeOfDay
                            ~ aspect + elevation, data = umfOven)

PsiAspectElev_pWindSky &lt;- occu( ~ wind + sky
                                ~ aspect + elevation,
                                data = umfOven,
                                starts = c(.6, -.4, .004, 2.3, -.15, -.07)
)

PsiAspectElev_pWindday &lt;- occu(~ wind + dayOfYear
                               ~ aspect + elevation, data = umfOven)

PsiAspectElev_pWindObs &lt;- occu( ~ wind + observer
                                ~ aspect + elevation,
                                data = umfOven,
                                starts = c(.6, -.4, .004, 2.3, -.15, -.62, -.97, -.12)
)

PsiAspectElev_pWindTime &lt;- occu( ~ wind + timeOfDay
                                 ~ aspect + elevation, data = umfOven)

PsiAspectElev_pSkyDay &lt;- occu( ~ sky + dayOfYear
                               ~ aspect + elevation, data = umfOven)

PsiAspectElev_pSkyObs &lt;- occu( ~ sky + observer
                              ~ aspect + elevation,
                              data = umfOven,
                              starts = c(.6, -.4, .004, 2.3, -.07, -.62, -.97, -.12)
)

PsiAspectElev_pSkyTime &lt;- occu(~ sky + timeOfDay
                               ~ aspect + elevation, data = umfOven)

PsiAspectElev_pDayofYearObs &lt;- occu(~ dayOfYear + observer
                                    ~ aspect + elevation, data = umfOven)

PsiAspectElev_pDayTime &lt;- occu(~ dayOfYear + timeOfDay
                               ~ aspect + elevation, data = umfOven)

PsiAspectElev_pObsTime &lt;- occu(~ observer + timeOfDay
                               ~ aspect + elevation, data = umfOven)

PsiAspectElev_pWindSkyDay &lt;- occu(~ wind + sky + dayOfYear
                                  ~ aspect + elevation, data = umfOven)

PsiAspectElev_pWindSkyObs &lt;- occu(~ wind + sky + observer
                                  ~ aspect + elevation,
                                  data = umfOven,
                                  starts = c(.6, -.4, .004, 2.3, -.15, -.07, -.62, -.97, -.12)
)

PsiAspectElev_pWindSkyTime &lt;- occu(~ wind + sky + timeOfDay
                                   ~ aspect + elevation, data = umfOven)

PsiAspectElev_pWindDayObs &lt;- occu(~ wind + dayOfYear + observer
                                  ~ aspect + elevation, data = umfOven)

PsiAspectElev_pWindDayTime &lt;- occu(~ wind + dayOfYear + timeOfDay
                                   ~ aspect + elevation, data = umfOven)

PsiAspectElev_pSkyDayObs &lt;- occu(~ sky + dayOfYear + observer
                                 ~ aspect + elevation, data = umfOven)

PsiAspectElev_pSkyDayTime &lt;- occu(~ sky + dayOfYear + timeOfDay
                                  ~ aspect + elevation, data = umfOven)
PsiAspectElev_pDayObsTime &lt;- occu( ~ dayOfYear + observer + timeOfDay
                                   ~ aspect + elevation, data = umfOven)

PsiAspectElev_pWindSkyDayObs &lt;- occu( ~ wind + sky + dayOfYear + observer
                                      ~ aspect + elevation, data = umfOven)

PsiAspectElev_pSkyDayObsTime &lt;- occu( ~ sky + dayOfYear + observer + timeOfDay
                                      ~ aspect + elevation, data = umfOven)

PsiAspectElev_pWindSkyObsTime &lt;- occu( ~ wind + sky + observer + timeOfDay
                                       ~ aspect + elevation, data = umfOven)</code></pre>
<pre class="r"><code>ObsModsP &lt;-
  fitList(
  PsiAspectElev_pdot,
  PsiAspectElev_pwind,
  PsiAspectElev_psky,
  PsiAspectElev_pobs,
  PsiAspectElev_pday,
  PsiAspectElev_ptime,
  PsiAspectElev_pWindSky,
  PsiAspectElev_pWindday,
  PsiAspectElev_pWindObs,
  PsiAspectElev_pWindTime,
  PsiAspectElev_pSkyDay,
  PsiAspectElev_pSkyObs,
  PsiAspectElev_pSkyTime,
  PsiAspectElev_pDayofYearObs,
  PsiAspectElev_pDayTime,
  PsiAspectElev_pObsTime,
  PsiAspectElev_pWindSkyDay,
  PsiAspectElev_pWindSkyObs,
  PsiAspectElev_pWindSkyTime,
  PsiAspectElev_pWindDayObs,
  PsiAspectElev_pWindDayTime,
  PsiAspectElev_pSkyDayObs,
  PsiAspectElev_pSkyDayTime,
  PsiAspectElev_pDayObsTime,
  PsiAspectElev_pWindSkyDayObs,
  PsiAspectElev_pSkyDayObsTime,
  PsiAspectElev_pWindSkyObsTime
  )

(ObsModsRankP &lt;- modSel(ObsModsP))</code></pre>
<pre><code>##                               nPars     AIC delta   AICwt cumltvWt
## PsiAspectElev_pWindObs            8 1441.83  0.00 3.2e-01     0.32
## PsiAspectElev_pWindDayObs         9 1442.72  0.89 2.0e-01     0.52
## PsiAspectElev_pWindSkyObs         9 1443.06  1.23 1.7e-01     0.69
## PsiAspectElev_pWindSkyDayObs     10 1444.18  2.35 9.7e-02     0.78
## PsiAspectElev_pWindSkyObsTime    10 1444.99  3.16 6.5e-02     0.85
## PsiAspectElev_pobs                7 1445.32  3.49 5.5e-02     0.90
## PsiAspectElev_pDayofYearObs       8 1446.99  5.16 2.4e-02     0.93
## PsiAspectElev_pSkyObs             8 1447.01  5.18 2.4e-02     0.95
## PsiAspectElev_pObsTime            8 1447.15  5.32 2.2e-02     0.97
## PsiAspectElev_pDayObsTime         9 1448.63  6.80 1.1e-02     0.98
## PsiAspectElev_pSkyDayObs          9 1448.65  6.82 1.0e-02     1.00
## PsiAspectElev_pSkyDayObsTime     10 1450.17  8.34 4.9e-03     1.00
## PsiAspectElev_pwind               5 1467.96 26.13 6.7e-07     1.00
## PsiAspectElev_pWindSky            6 1469.54 27.71 3.0e-07     1.00
## PsiAspectElev_pWindday            6 1469.57 27.73 3.0e-07     1.00
## PsiAspectElev_pWindTime           6 1470.03 28.20 2.4e-07     1.00
## PsiAspectElev_psky                5 1470.21 28.38 2.2e-07     1.00
## PsiAspectElev_pday                5 1470.51 28.68 1.9e-07     1.00
## PsiAspectElev_pdot                4 1470.51 28.68 1.9e-07     1.00
## PsiAspectElev_ptime               5 1470.62 28.79 1.8e-07     1.00
## PsiAspectElev_pWindSkyDay         7 1470.67 28.84 1.7e-07     1.00
## PsiAspectElev_pWindSkyTime        7 1471.49 29.66 1.1e-07     1.00
## PsiAspectElev_pWindDayTime        7 1471.59 29.76 1.1e-07     1.00
## PsiAspectElev_pDayTime            6 1472.07 30.24 8.5e-08     1.00
## PsiAspectElev_pSkyDay             6 1472.42 30.59 7.2e-08     1.00
## PsiAspectElev_pSkyTime            6 1472.44 30.61 7.1e-08     1.00
## PsiAspectElev_pSkyDayTime         7 1474.16 32.33 3.0e-08     1.00</code></pre>
<p>
<p>We can see from our model selection table that in the end, only wind level and observer are important covariates in determining probability of detection of ovenbirds across our site. Let’s move forward with some interpretation of what seems to be our best supported model, <code>PsiAspectElev_pWindObs</code>.</p>
</div>
<div id="model-interpretation-and-value-prediction" class="section level3">
<h3>Model Interpretation and Value Prediction</h3>
<p>
<p>We can first look at a basic summary of this model using the <code>summary</code> function. Remember that we can look at just the coefficients with the <code>coef</code> function as well.</p>
<pre class="r"><code>summary(PsiAspectElev_pWindObs)</code></pre>
<pre><code>## 
## Call:
## occu(formula = ~wind + observer ~ aspect + elevation, data = umfOven, 
##     starts = c(0.6, -0.4, 0.004, 2.3, -0.15, -0.62, -0.97, -0.12))
## 
## Occupancy (logit-scale):
##             Estimate      SE     z  P(&gt;|z|)
## (Intercept)  0.54989 0.74340  0.74 0.459485
## aspect      -0.38992 0.10830 -3.60 0.000318
## elevation    0.00438 0.00124  3.52 0.000431
## 
## Detection (logit-scale):
##             Estimate     SE      z  P(&gt;|z|)
## (Intercept)    1.459 0.1684  8.664 4.56e-18
## wind          -0.140 0.0581 -2.404 1.62e-02
## observerCH    -0.610 0.2001 -3.047 2.31e-03
## observerDJW   -0.960 0.1928 -4.978 6.43e-07
## observerJDW   -0.132 0.2212 -0.598 5.50e-01
## 
## AIC: 1441.831 
## Number of sites: 296
## optim convergence code: 0
## optim iterations: 79 
## Bootstrap iterations: 0</code></pre>
<p>
We can see, based on coefficient values, that as wind level increases, probability of detection decreases. Regarding observer, we see that observer AJS is not shown in the coefficient list. This means that the detection probability parameter of AJS is accounted for in the intercept term. The values of the other coefficients are relative to this AJS baseline. The other three observers show lower detection probabilities than AJS, this being a substantial difference in the case of CH and DJW.<br />

<p>
<p>We can use the <code>predict</code> function to look at estimated probabilities of detection and occupancy based on our actual site data. We need to set the type of estimate of we want as either “state” for occupancy values or “det” for detection probability.This will show us values for all 296 sites, so let’s use the <code>head</code> function to show just the first 20.</p>
<pre class="r"><code>head(predict(PsiAspectElev_pWindObs, type = &quot;state&quot;), 20)</code></pre>
<pre><code>##    Predicted         SE     lower     upper
## 1  0.9830955 0.00899099 0.9526985 0.9940801
## 2  0.9773647 0.01091637 0.9425797 0.9912722
## 3  0.9659182 0.01415440 0.9242545 0.9850359
## 4  0.8797440 0.04744408 0.7523252 0.9462907
## 5  0.8988999 0.04122739 0.7851473 0.9558160
## 6  0.9162934 0.03619232 0.8127792 0.9650367
## 7  0.8836914 0.05016752 0.7448249 0.9518700
## 8  0.8656616 0.05004262 0.7349181 0.9374117
## 9  0.8671167 0.04580649 0.7496115 0.9343101
## 10 0.8090537 0.05955044 0.6656010 0.9001948
## 11 0.7828257 0.06392079 0.6330435 0.8827903
## 12 0.9663072 0.01386372 0.9256425 0.9850913
## 13 0.9584204 0.01567954 0.9142381 0.9803308
## 14 0.7642523 0.04735424 0.6594847 0.8443915
## 15 0.7452092 0.05185131 0.6313436 0.8331973
## 16 0.9168642 0.02292883 0.8594721 0.9521229
## 17 0.7850560 0.03623023 0.7056938 0.8476380
## 18 0.8209871 0.02902843 0.7569306 0.8710387
## 19 0.9366686 0.01742950 0.8926475 0.9633789
## 20 0.9503998 0.01650266 0.9060855 0.9743950</code></pre>
<p>
<p>Keep in mind these values can be associated back to our site covariates in <code>obsCovs</code> and <code>siteCovs</code>, in the order they appear there, but the row numbers here do not represent actual site numbers. In others words row 10 here is not necessarily our site #10, but it is the 10th site in our siteCovs file. We can summarize our predicted values to see the range of predicted occupancy values.</p>
<pre class="r"><code>summary(predict(PsiAspectElev_pWindObs, type = &quot;state&quot;))</code></pre>
<pre><code>##    Predicted            SE               lower            upper       
##  Min.   :0.5155   Min.   :0.008106   Min.   :0.3206   Min.   :0.7058  
##  1st Qu.:0.8308   1st Qu.:0.017078   1st Qu.:0.7430   1st Qu.:0.8927  
##  Median :0.9136   Median :0.022239   Median :0.8553   Median :0.9519  
##  Mean   :0.8782   Mean   :0.030718   Mean   :0.8047   Mean   :0.9270  
##  3rd Qu.:0.9473   3rd Qu.:0.037345   3rd Qu.:0.9010   3rd Qu.:0.9721  
##  Max.   :0.9857   Max.   :0.104421   Max.   :0.9571   Max.   :0.9953</code></pre>
<p>
<p>We can see that our minimum predicted site occupancy value is 51.5%, but average site occupancy across our sites is 87.8%. Why is this so close to our naive occupancy estimate? To find out, let’s look at our detection probability estimates.</p>
<pre class="r"><code>head(predict(PsiAspectElev_pWindObs, type = &quot;det&quot;), 20)</code></pre>
<pre><code>##    Predicted         SE     lower     upper
## 1  0.5547656 0.03428648 0.4869729 0.6205798
## 2  0.8114214 0.02577302 0.7556821 0.8568530
## 3  0.6223301 0.03039551 0.5611872 0.6798144
## 4  0.7903354 0.02900567 0.7278753 0.8415795
## 5  0.5547656 0.03428648 0.4869729 0.6205798
## 6  0.8114214 0.02577302 0.7556821 0.8568530
## 7  0.6223301 0.03039551 0.5611872 0.6798144
## 8  0.7662392 0.02956858 0.7034217 0.8191718
## 9  0.5200374 0.04371529 0.4346066 0.6043121
## 10 0.8114214 0.02577302 0.7556821 0.8568530
## 11 0.6223301 0.03039551 0.5611872 0.6798144
## 12 0.7903354 0.02900567 0.7278753 0.8415795
## 13 0.5200374 0.04371529 0.4346066 0.6043121
## 14 0.8114214 0.02577302 0.7556821 0.8568530
## 15 0.6223301 0.03039551 0.5611872 0.6798144
## 16 0.7903354 0.02900567 0.7278753 0.8415795
## 17 0.4851143 0.05519897 0.3792586 0.5923227
## 18 0.8114214 0.02577302 0.7556821 0.8568530
## 19 0.6223301 0.03039551 0.5611872 0.6798144
## 20 0.7903354 0.02900567 0.7278753 0.8415795</code></pre>
<pre class="r"><code>summary(predict(PsiAspectElev_pWindObs, type = &quot;det&quot;))</code></pre>
<pre><code>##    Predicted            SE              lower            upper       
##  Min.   :0.4851   Min.   :0.02501   Min.   :0.3793   Min.   :0.5923  
##  1st Qu.:0.6223   1st Qu.:0.02901   1st Qu.:0.5612   1st Qu.:0.6798  
##  Median :0.7005   Median :0.02972   Median :0.6371   Median :0.7569  
##  Mean   :0.6999   Mean   :0.03122   Mean   :0.6353   Mean   :0.7572  
##  3rd Qu.:0.7891   3rd Qu.:0.03067   3rd Qu.:0.7279   3rd Qu.:0.8340  
##  Max.   :0.8114   Max.   :0.07009   Max.   :0.7557   Max.   :0.8569</code></pre>
<p>
Predicted detection probability, per ocassion, is between 48.5% and 81.1%. The mean across our sites is 69.9%. If this is the probability of detecting an ovenbird, when present, within a single occassion, what is the probability of missing a bird, on all 4 ocassions? <span class="math display">\[Pr(0000 | \Psi = 1, p) = (1-p_0) * (1-p_1) * (1-p_2) * (1-p_3)\]</span> <span class="math display">\[ = (1-p)^4\]</span>
<p>
<p>For our scenario this value is 0.008.</p>
<p>
<p>If we subtract this value from 1, we get “pcap” or p prime, which is the probability of seeing an ovenbird at least once across the 4 ocassions, if the site is occupied. This value is 0.992. And so it follows that our naive occupancy should be very similar to our estimated probability of occupancy for this species. It is VERY unlikely that an observer would visit a site occupied by ovenbirds 4 times, and never detect a single ovenbird.</p>
</div>
<div id="graphical-interpretation-of-model-covariates" class="section level3">
<h3>Graphical Interpretation of Model Covariates</h3>
<p>
<p>Let’s now take a look at how our covariates influence occupancy and detection. We know that as wind increases, probability of detection decreases, but we can create a response curve which allows us to visualize how dramatic this effect is, across a set of values of wind. To do this we use the predict function, but this time we provide the set of values we want to use for the prediction. We will vary the values of wind from its minimum to its maximum. In order to graphically show its effect though, we need to hold the other covariates constant.</p>
<p>
<p>Let’s first save our best model with a shorter name.</p>
<pre class="r"><code>best &lt;- PsiAspectElev_pWindObs</code></pre>
<p>
<p>To predict across a particular set of values using our model equation, we need to create a new dataframe. Remember the names of your columns here need to be exactly the same as the names of your covariates in the unmarked data objects.Here we are predicting across all possible values of the wind covariate (0-6), and setting the observer to “AJS”.</p>
<pre class="r"><code>newDataDetWind_AJS &lt;- data.frame(wind = seq(0, 6),
                                 observer = factor(&quot;AJS&quot;,
                                 levels = c(&quot;AJS&quot;, &quot;CH&quot;, &quot;DJW&quot;, &quot;JDW&quot;)))
head(newDataDetWind_AJS)                                               </code></pre>
<pre><code>##   wind observer
## 1    0      AJS
## 2    1      AJS
## 3    2      AJS
## 4    3      AJS
## 5    4      AJS
## 6    5      AJS</code></pre>
<p>
<p>We will now use this dataframe to create predictions of detection probability, using our equation from our best model.</p>
<pre class="r"><code>EstDetWindAJS &lt;- predict(best,
                         type = &quot;det&quot;,
                         newdata = newDataDetWind_AJS,
                         appendData = TRUE)
head(EstDetWindAJS)</code></pre>
<pre><code>##   Predicted         SE     lower     upper wind observer
## 1 0.8114214 0.02577302 0.7556821 0.8568530    0      AJS
## 2 0.7891018 0.02501179 0.7359358 0.8339783    1      AJS
## 3 0.7649059 0.02760332 0.7065964 0.8146668    2      AJS
## 4 0.7388528 0.03413261 0.6667002 0.8000698    3      AJS
## 5 0.7110033 0.04396468 0.6179607 0.7891189    4      AJS
## 6 0.6814643 0.05619719 0.5629385 0.7803868    5      AJS</code></pre>
<p>Let’s repeat this for the other three observers.</p>
<pre class="r"><code>newDataDetWind_CH &lt;- data.frame(wind = seq(0, 6),
                                observer = factor(&quot;CH&quot;, levels = c(&quot;AJS&quot;, &quot;CH&quot;, &quot;DJW&quot;, &quot;JDW&quot;)))

EstDetWindCH &lt;- predict(best,
                        type = &quot;det&quot;,
                        newdata = newDataDetWind_CH,
                        appendData = TRUE)

newDataDetWind_DJW &lt;- data.frame(wind = seq(0, 6),
                                 observer = factor(&quot;DJW&quot;,
                                 levels = c(&quot;AJS&quot;, &quot;CH&quot;, &quot;DJW&quot;, &quot;JDW&quot;)))
EstDetWindDJW &lt;- predict(best,
                         type = &quot;det&quot;,
                         newdata = newDataDetWind_DJW,
                         appendData = TRUE)

newDataDetWind_JDW &lt;- data.frame(wind = seq(0, 6),
                                 observer = factor(&quot;JDW&quot;,
                                 levels = c(&quot;AJS&quot;, &quot;CH&quot;, &quot;DJW&quot;, &quot;JDW&quot;)))
EstDetWindJDW &lt;- predict(best,
                         type = &quot;det&quot;,
                         newdata = newDataDetWind_JDW,
                         appendData = TRUE)</code></pre>
<p>
<p>Now we have predicted values of detection probability for all values of wind, and for all values of oberver. Let’s graph them together to see what the relationships look like.</p>
<pre class="r"><code>#AJS
plot(
  Predicted ~ wind,
  EstDetWindAJS,
  type = &quot;l&quot;,
  ylim = c(0, 1),
  xlab = &quot;Wind Level&quot;,
  ylab = &quot;Expected detection probability&quot;,
  las = 1,
  bty = &quot;n&quot;
  )
#Upper and Lower Confidence Intervals
lines(
  lower ~ wind,
  EstDetWindAJS,
  type = &quot;l&quot;,
  lty = 3
  )
lines(
  upper ~ wind,
  EstDetWindAJS,
  type = &quot;l&quot;,
  lty = 3
  )
      
#CH
lines(
  Predicted ~ wind,
  EstDetWindCH,
  type = &quot;l&quot;,
  col = &quot;green&quot;
  )
lines(
  lower ~ wind,
  EstDetWindCH,
  type = &quot;l&quot;,
  col = &quot;green&quot;,
  lty = 3
  )
lines(
  upper ~ wind,
  EstDetWindCH,
  type = &quot;l&quot;,
  col = &quot;green&quot;,
  lty = 3
  )

#DJW
lines(
  Predicted ~ wind,
  EstDetWindDJW,
  type = &quot;l&quot;,
  col = &quot;red&quot;
  )

lines(
  lower ~ wind,
  EstDetWindDJW,
  type = &quot;l&quot;,
  col = &quot;red&quot;,
  lty = 3
  )
lines(
  upper ~ wind,
  EstDetWindDJW,
  type = &quot;l&quot;,
  col = &quot;red&quot;,
  lty = 3
  )

#JDW
lines(
  Predicted ~ wind,
  EstDetWindJDW,
  type = &quot;l&quot;,
  col = &quot;blue&quot;
  )

lines(
  lower ~ wind,
  EstDetWindJDW,
  type = &quot;l&quot;,
  col = &quot;blue&quot;,
  lty = 3
  )

lines(
  upper ~ wind,
  EstDetWindJDW,
  type = &quot;l&quot;,
  col = &quot;blue&quot;,
  lty = 3
  )

legend(
  &quot;bottomleft&quot;,
  legend = c(&quot;AJS&quot;, &quot;CH&quot;, &quot;DJW&quot;, &quot;JDW&quot;),
  lty = 1,
  col = c(&quot;black&quot;, &quot;green&quot;, &quot;red&quot;, &quot;blue&quot;),
  bty = &quot;n&quot;
  )</code></pre>
<img src="OccupancyDemo_Oven_files/figure-html/unnamed-chunk-26-1.png" width="672" />
<p>
While interpreting the model coefficients directly can be tricky, we can now see clearly that DJW had the lowest detection probability, and both AJS and JDW displayed similarly high relative detection probablity. We can also now see how wind level affects detection probability.
<p>
<p>But typically detection covariates are not the part of the model we are most interested. We tpyically want to know how covariates influence occupancy. Let’s now look at how aspect and elevation influence ovenbird occupancy. As above we need to first create a new dataframe. Let’s start with looking at our most important covariates, aspect and elevation. Our model for occupancy has two covariates, so that is what we need in the new dataframe.We need two separate dataframes though, one which allows aspect to vary and holds elevation constant, the other which allows elevation to vary.</p>
<pre class="r"><code>newDataOccAspect &lt;-
  data.frame(
  aspect = seq(min(siteCovs$aspect), max(siteCovs$aspect), length.out = 100),
  elevation = median(siteCovs$elevation)
  )
EstOccAspect &lt;- predict(best,
                        type = &quot;state&quot;,
                        newdata = newDataOccAspect,
                        appendData = TRUE)
head(EstOccAspect)</code></pre>
<pre><code>##   Predicted         SE     lower     upper     aspect elevation
## 1 0.9617035 0.01534509 0.9173393 0.9827062 0.01254071  611.2705
## 2 0.9607940 0.01547159 0.9163627 0.9820832 0.07516437  611.2705
## 3 0.9598638 0.01559622 0.9153715 0.9814391 0.13778803  611.2705
## 4 0.9589124 0.01571892 0.9143653 0.9807734 0.20041169  611.2705
## 5 0.9579395 0.01583959 0.9133438 0.9800854 0.26303535  611.2705
## 6 0.9569446 0.01595817 0.9123064 0.9793745 0.32565901  611.2705</code></pre>
<pre class="r"><code>newDataOccElev &lt;- data.frame(
  aspect = median(siteCovs$aspect),
  elevation = seq(
  min(siteCovs$elevation),
  max(siteCovs$elevation),
  length.out = 100
  )
  )
EstOccElev &lt;- predict(best,
                      type = &quot;state&quot;,
                      newdata = newDataOccElev,
                      appendData = TRUE)
head(EstOccElev)</code></pre>
<pre><code>##   Predicted         SE     lower     upper   aspect elevation
## 1 0.6764097 0.09280446 0.4765922 0.8275470 2.351254  252.0147
## 2 0.6829948 0.09020303 0.4877560 0.8297878 2.351254  258.9181
## 3 0.6895074 0.08762241 0.4989088 0.8320184 2.351254  265.8216
## 4 0.6959458 0.08506553 0.5100382 0.8342391 2.351254  272.7251
## 5 0.7023083 0.08253521 0.5211319 0.8364503 2.351254  279.6286
## 6 0.7085935 0.08003416 0.5321777 0.8386525 2.351254  286.5321</code></pre>
<p>
<p>Now let’s graph the relationships.</p>
<pre class="r"><code>par(mfrow = c(1,2))
#Aspect
plot(
  Predicted ~ aspect,
  EstOccAspect,
  type = &quot;l&quot;,
  col = &quot;red&quot;,
  ylim = c(0, 1),
  xlab = &quot;Aspect&quot;,
  ylab = &quot;Expected occupancy probability&quot;,
  las = 1,
  bty = &quot;n&quot;
  )

lines(
  lower ~ aspect,
  EstOccAspect,
  type = &quot;l&quot;,
  lty = 2,
  col = &quot;red&quot;
  )
lines(
  upper ~ aspect,
  EstOccAspect,
  type = &quot;l&quot;,
  lty = 2,
  col = &quot;red&quot;
  )
#Elevation
plot(
  Predicted ~ elevation,
  EstOccElev,
  type = &quot;l&quot;,
  col = &quot;blue&quot;,
  ylim = c(0, 1),
  xlab = &quot;Elevation (m)&quot;,
  ylab = &quot;Expected occupancy probability&quot;,
  las = 1,
  bty = &quot;n&quot;
  )

lines(
  lower ~ elevation,
  EstOccElev,
  type = &quot;l&quot;,
  lty = 2,
  col = &quot;blue&quot;
  )
lines(
  upper ~ elevation,
  EstOccElev,
  type = &quot;l&quot;,
  lty = 2,
  col = &quot;blue&quot;
  )</code></pre>
<img src="OccupancyDemo_Oven_files/figure-html/unnamed-chunk-28-1.png" width="672" /> ________________________________________________________________________________________________ <img style="float:right" src="images/radians.gif" />
<p>
<p>A Note about Aspect: You’ll notice aspect ranges from around zero to a bit more than 6. Aspect here was recorded in radians, which can be converted to degrees by multiplying the value by 180 degrees and dividing by Pi. Refer to the figure here to see what these radian values refer to, in terms of cardinal directions. As you can see, a value near zero represents east, with increasing values moving counterclockwise. Do you see any potential issues with how we have analyzed aspect here?</p>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
